# Generated by Django 4.0.4 on 2022-05-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('modify_right', models.IntegerField()),
                ('share_right', models.IntegerField()),
                ('discuss_right', models.IntegerField()),
                ('others_modify_right', models.IntegerField()),
                ('others_share_right', models.IntegerField()),
                ('others_discuss_right', models.IntegerField()),
                ('recycled', models.IntegerField()),
                ('is_occupied', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.document')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.group')),
                ('receiver_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_receiver',
                                   to='server.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_sender',
                                                to='server.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('receiver_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_receiver',
                                   to='server.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_sender',
                                                to='server.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.CreateModel(
            name='DocumentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watch', models.DateTimeField()),
                ('favorite', models.IntegerField()),
                ('modified_time', models.IntegerField()),
                ('type', models.IntegerField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.group'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.document')),
            ],
        ),
    ]
