# Generated by Django 4.0.4 on 2022-05-11 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='documentuser',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='documentuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='leader_id',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
